# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "amqp-hermes"
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Hartog C. de Mik"]
  s.date = "2012-03-01"
  s.description = "Wrapper around ruby-amqp to make pub/sub easier"
  s.email = "hartog.de.mik@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/amqp-hermes.rb",
    "lib/amqp-hermes/connectivity.rb",
    "lib/amqp-hermes/message.rb",
    "lib/amqp-hermes/receiver.rb",
    "lib/amqp-hermes/transmitter.rb",
    "lib/amqp-hermes/version.rb",
    "spec/amqp-hermes/connectivity_spec.rb",
    "spec/amqp-hermes/receiver_spec.rb",
    "spec/amqp-hermes/transmitter_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/wyngle/amqp-hermes"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.16"
  s.summary = "Hermes; Messenger of the gods"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency "amqp"
      s.add_development_dependency "rspec"
      s.add_development_dependency "faker"
      s.add_development_dependency "rdoc"
      s.add_development_dependency "bundler"
      s.add_development_dependency "jeweler"
    else
      s.add_dependency "amqp"
      s.add_dependency "rspec"
      s.add_dependency "faker"
      s.add_dependency "rdoc"
      s.add_dependency "bundler"
      s.add_dependency "jeweler"
    end
  else
    s.add_dependency "amqp"
    s.add_dependency "rspec"
    s.add_dependency "faker"
    s.add_dependency "rdoc"
    s.add_dependency "bundler"
    s.add_dependency "jeweler"
  end
end

